parameters:
  SolutionBaseName:
  BuildConfiguration:
  TargetProjects: 'src/**/*.csproj'

jobs:
- job: CodeBuild
  pool:
    name: SLD Build pool
  variables:
  - group: BUILD Management Resources
  - name: SolutionBaseName
    value: SFA.DAS.Payments.DataLocks
  steps:
  - template: /azure-pipelines-templates/build/step/gitversion.yml


  # task: DotNetCoreCLI@2
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: ${{ parameters.TargetProjects }}
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.DataLocks.ServiceFabric/SFA.DAS.Payments.DataLocks.ServiceFabric.sfproj
  #- task: DotNetCoreCLI@2
  # displayName: Restore - src/SFA.DAS.Payments.DataLocks.ServiceFabric/SFA.DAS.Payments.DataLocks.ServiceFabric.sfproj
  #  inputs:
  #    command: restore
  #    projects: src/SFA.DAS.Payments.DataLocks.ServiceFabric/SFA.DAS.Payments.DataLocks.ServiceFabric.sfproj
  #    noCache: true
  #    feedsToUse: 'select'
  #    vstsFeed: 'dct-pkg'




  # task: NuGetCommand@2 - src/SFA.DAS.Payments.DataLocks.Messages/SFA.DAS.Payments.DataLocks.Messages.csproj
  - task: NuGetCommand@2
    displayName: Restore - src/SFA.DAS.Payments.DataLocks.Messages/SFA.DAS.Payments.DataLocks.Messages.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.DataLocks.Messages/SFA.DAS.Payments.DataLocks.Messages.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: NuGetCommand@2 - src/SFA.DAS.Payments.DataLocks.Model/SFA.DAS.Payments.DataLocks.Model.csproj
  - task: NuGetCommand@2
    displayName: Restore - src/SFA.DAS.Payments.DataLocks.Model/SFA.DAS.Payments.DataLocks.Model.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.DataLocks.Model/SFA.DAS.Payments.DataLocks.Model.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: NuGetCommand@2 - src/SFA.DAS.Payments.DataLocks.Messages.Internal/SFA.DAS.Payments.DataLocks.Messages.Internal.csproj
  - task: NuGetCommand@2
    displayName: Restore - src/SFA.DAS.Payments.DataLocks.Messages.Internal/SFA.DAS.Payments.DataLocks.Messages.Internal.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.DataLocks.Messages.Internal/SFA.DAS.Payments.DataLocks.Messages.Internal.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: NuGetCommand@2 - src/SFA.DAS.Payments.DataLocks.DataLockService.Interfaces/SFA.DAS.Payments.DataLocks.DataLockService.Interfaces.csproj
  - task: NuGetCommand@2
    displayName: Restore - src/SFA.DAS.Payments.DataLocks.DataLockService.Interfaces/SFA.DAS.Payments.DataLocks.DataLockService.Interfaces.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.DataLocks.DataLockService.Interfaces/SFA.DAS.Payments.DataLocks.DataLockService.Interfaces.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'



  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  ${{ parameters.TargetProjects }}
      arguments: '--configuration $(buildConfiguration) --no-restore'

  #- task: DotNetCoreCLI@2
  #  displayName: Build
  #  inputs:
  #    projects:  src/SFA.DAS.Payments.DataLocks.ServiceFabric/SFA.DAS.Payments.DataLocks.ServiceFabric.sfproj
  #    arguments: '--configuration $(buildConfiguration) --no-restore'



  - task: DotNetCoreCLI@2
    displayName: "Publish $(SolutionBaseName)"
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.Payments.DataLocks.Messages/SFA.DAS.Payments.DataLocks.Messages.csproj
      arguments: "-o $(build.artifactstagingdirectory)/publish -c $(BuildConfiguration) --no-restore --no-build"
      modifyOutputPath: true

  - task: DotNetCoreCLI@2
    displayName: "Publish $(SolutionBaseName)"
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.Payments.DataLocks.Model/SFA.DAS.Payments.DataLocks.Model.csproj
      arguments: "-o $(build.artifactstagingdirectory)/publish -c $(BuildConfiguration) --no-restore --no-build"
      modifyOutputPath: true

  - task: DotNetCoreCLI@2
    displayName: "Publish $(SolutionBaseName)"
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.Payments.DataLocks.Messages.Internal/SFA.DAS.Payments.DataLocks.Messages.Internal.csproj
      arguments: "-o $(build.artifactstagingdirectory)/publish -c $(BuildConfiguration) --no-restore --no-build"
      modifyOutputPath: true

  - task: DotNetCoreCLI@2
    displayName: "Publish $(SolutionBaseName)"
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.Payments.DataLocks.DataLockService.Interfaces/SFA.DAS.Payments.DataLocks.DataLockService.Interfaces.csproj
      arguments: "-o $(build.artifactstagingdirectory)/publish -c $(BuildConfiguration) --no-restore --no-build"
      modifyOutputPath: true


      
  - task: CopyFiles@2
    displayName: Copy Files to $(build.artifactstagingdirectory)/publish
    inputs:
      Contents: |
        azure/**
      TargetFolder: $(build.artifactstagingdirectory)/publish
      OverWrite: true

  - task: PublishPipelineArtifact@1
    displayName: Publish Build Artifact
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: drop

  - template: /azure-pipelines-templates/build/step/nuget-pack.yml
    parameters:
      DotNetStandardPackagesToPack: |
        src/SFA.DAS.Payments.DataLocks.Messages/SFA.DAS.Payments.DataLocks.Messages.csproj;
        src/SFA.DAS.Payments.DataLocks.Model/SFA.DAS.Payments.DataLocks.Model.csproj;
        src/SFA.DAS.Payments.DataLocks.Messages.Internal/SFA.DAS.Payments.DataLocks.Messages.Internal.csproj;
        src/SFA.DAS.Payments.DataLocks.DataLockService.Interfaces/SFA.DAS.Payments.DataLocks.DataLockService.Interfaces.csproj;